- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.13.1/prometheus-{{version}}.linux-amd64.tar.gz
    dest: /opt/prometheus-{{version}}.linux-amd64.tar.gz

- name: Create prometheus dir
  file:
    state: directory
    path: /opt/prometheus
    mode: '0755'

- name: Check prometheus.yml existance
  stat:
    path: /opt/prometheus/prometheus.yml
  register: stat_result

- name: Extract tar
  unarchive:
    src: /opt/prometheus-{{version}}.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: stat_result.stat.exists == False

- name: Create prometheus service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - start prometheus

- name: Configure prometheus
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
  notify:
    - restart prometheus
