- name: Install dependencies
  apt:
    package: "{{package}}"

- name: Download grafana
  get_url:
    url: '{{grafana_link}}'
    dest: /opt/{{grafana_deb}}

- name: Install grafana
  apt:
    deb: /opt/{{grafana_deb}}

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
