- name: Extract the tar
  unarchive:
    src: /opt/prometheus-{{version}}.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: restart systemd
  shell: "systemctl daemon-reload"

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
