- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-{{version}}.linux-amd64.tar.gz
    dest: /opt/node_exporter-{{version}}.linux-amd64.tar.gz

- name: Create node_exporter dir
  file:
    state: directory
    path: /opt/node_exporter
    mode: '0755'

- name: Extract the archive
  unarchive:
    src: /opt/node_exporter-{{version}}.linux-amd64.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: systemd node Exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
