- name: reload systemd
  shell: "systemctl daemon-reload"

- name: start testPing
  service:
    name: testPing
    state: started
    
- name: restart telegraf
  service:
    name: telegraf
    state: restarted
    enabled: yes
