---
- name: Wordpress setup
  hosts: devices
  remote_user: user
  become: yes
  vars_files:
    - "variables/wp"
    - "variables/apache"
  tasks:
  - name: Create webroot
    file:
      state: directory
      path: /var/www/html/{{ server_hostname }}
      owner: www-data
      group: www-data
      mode: 0755

  - name: Check if WordPress directory exists in /var/www
    stat: 
      path: /var/www/html/{{ server_hostname }}/wp-content/
    register: check_path

  - name: Download WordPress
    get_url: 
      url: https://wordpress.org/latest.tar.gz 
      dest: /tmp/wordpress-latest.tar.gz

  - name: Extract WordPress to webroot
    unarchive:
      src: /tmp/wordpress-latest.tar.gz
      dest: /var/www/html/{{ server_hostname }}
      owner: www-data
      group: www-data
      copy: no
      extra_opts: [--strip-components=1]

  - name: Fetch random salts for WordPress config
    command: curl https://api.wordpress.org/secret-key/1.1/salt/
    args:
      warn: no
    register: "wp_salt"
    when: not check_path.stat.exists

  - name: Add wp-config
    template:
      src: templates/wp-config.php
      dest: /var/www/html/{{server_hostname}}/wp-config.php
    when: not check_path.stat.exists