---
 - name: Check file exists
   stat:
     path: "/root/go/src/{{bind_exporter_link}}/bind_exporter.go"
   register: stat_result

 - name: Get bind exporter
   shell: "go get {{bind_exporter_link}}"
   when: stat_result.stat.exists == False

 - name: Copy binary
   copy:
     src: /root/go/bin/bind_exporter
     dest: /usr/local/bin/bind_exporter
     mode: u=rwx,g=rx,o=rx
     remote_src: yes

 - name: Create service
   template:
     src: bind_exporter.service.j2
     dest: /etc/systemd/system/bind_exporter.service
   notify:
     - restart systemd
     - start bind_exporter
