---
 - name: Download go
   get_url:
     url: "{{go_link}}"
     dest: /opt/{{go_tar}}

 - name: Create dir
   file:
     path: /opt/go
     state: directory
     mode: '0755'

 - name: Extract go
   unarchive:
     src: /opt/{{go_tar}}
     dest: /opt/go
     remote_src: yes
     extra_opts:
       - --strip-components=1

 - name: Create sym-link
   file:
     src: /opt/go/bin/go
     dest: /usr/local/bin/go
     state: link

 - name: Verifiy file exists
   stat:
     path: "/root/go/src/{{apache_exporter_link}}.go"
   register: stat_result

 - name: Download the apache_exporter
   shell: "go get {{apache_exporter_link}}"
   when: stat_result.stat.exists == True

 - name: Copy the binary file
   copy:
     src: /root/go/bin/apache_exporter
     dest: /usr/local/bin/apache_exporter
     mode: u=rwx,g=rx,o=rx
     remote_src: yes

 - name: Create the apache_exporter.service
   template:
     src: apache_exporter.service.j2
     dest: /etc/systemd/system/apache_exporter.service
   notify:
     - restart systemd
     - start apache_exporter
