---
  - name: stop systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: no

  - name: get timestamp
    shell: date +%s
    register: ts

  - name: configuring db
    template:
      src: db.sbo.j2
      dest: /etc/bind/db.sbo

  - name: configuring reverse db
    template:
      src: db.sbo.ptr.j2
      dest: /etc/bind/db.sbo.ptr

  - name: bind reload db
    shell: rndc reload

  - name: restart bind
    service:
      name: bind9
      state: restarted

  - name: check conf
    shell: named-checkconf
